// This file is a placeholder used to store Firebase configuration generated by
// the FlutterFire CLI (`flutterfire configure`). Do NOT commit real API keys
// to public repositories. To generate this file run in your project root:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// The CLI will create a proper `DefaultFirebaseOptions` class here. For now
// this placeholder throws a helpful error if used so that web initialization
import 'package:firebase_core/firebase_core.dart';

// surfaces a clear message instead of failing silently.

class DefaultFirebaseOptions {
  static const String _missing =
      'DefaultFirebaseOptions not configured. Run `flutterfire configure` in the project root and import the generated file.';

  // Accessing this on web without replacing this placeholder will throw.
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(_missing);
  }
}

